name: publish
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: checkout
        run: |
          echo 'Current tag: ${{ github.ref_name }}'
          echo 'Current commit: ${{ github.sha }}'
      - name: publish to crates.io
        run: |
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
